language: node_js
node_js:
- '4'
- '5'
notifications:
  slack:
    secure: Ks+rjE2TZwVZLWQoRQO6aak7PIUA5x31R67VXezfFh8h5fzJbzLI7cyUK1aNbjROX0VDWrOq4QdzYIWoftKM+YmWzzGf/Dj9plw5pz9TzmAuCjCRbEY9Ukpr5L7JzvAJZQIHCeByuM8/QBv/DZAwqOJGafq3BwOZGKWNMr3/hsnx6Kg/idiTZZK5lan8Y4c9QvqMx0rXQ4CEXk4jVpOMtoWSqIFWvwbWdtbaflfoFllgSJP3IEX+RmFUDcdAok85K+CYlGTwUggZHliYYFVLPdtMz3prIdv9S1JXzZh+AYhste9Jw2Zfs7mi7Y8nC/8Z14CvozszEIqt9ggyVopBaZHXOY3r5SfHbgtyAjzGkaqxBpT6Clp7t+AXQ9eKKkVecw3hbSopX2MaI2QrxMQIObneH6bjCTFhD1EIAr1Oj+sbwAP2rvFg8EtNdfuO6ah8oQVvy5M/KIjwS5E2V48fTQQCRaV0q3wTkFG65PonXM0u03zrbtnM7B8XVpRBOWgP11UhWknL2C/TyTOCd1doK1Jyc3799Le6mdK73kbV/zxEwvs9BjyZ7YCYoIFnGKedPwXFVRhfWLwxzwzdAYTH3sV6O629a7y7P/FVODNr2gLfadvUS3rGjmAtkapv+2k90Sg1CcxdI0x5KotLmbfkbqxYrTgbGAft0YKP5/A/b4c=
